export enum PlatformWebsiteCategoryEnum {
    official = 1,
    wikia = 2,
    wikipedia = 3,
    facebook = 4,
    twitter = 5,
    twitch = 6,
    instagram = 8,
    youtube = 9,
    iphone = 10,
    ipad = 11,
    android = 12,
    steam = 13,
    reddit = 14,
    discord = 15,
    google_plus = 16,
    tumblr = 17,
    linkedin = 18,
    pinterest = 19,
    soundcloud = 20,
}